### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by xstefen** [karyfoundation/themeX#6]
This thing dead? `themex init` prompts you to visit a non-existent wiki. Cant seem to get it to do anything

**Comment by pouyakary** [comment]
Unfortunately i have lost my ownership of the npm account and I cannot recover it. The project is not actively developed but my own theme Pro Colors runs on this package and so I maintain it. You have to clone the repo and build it yourself. And if you want to do anything with it I suggest you clone [this repo](https://github.com/pouyakary/ProColors) and build upon it. It's probably the only project that is using themeX and is being developed for years so is rock solid.

**Comment by pouyakary** [comment]
Ooh and remember the structure of the project is:

```
 your-project-name.themeX
 └─ theme.yml
```

When you want to build you do `themex ./your-project-nam.themeX` like on OS X bundle

**Comment by xstefen** [comment]
Thanks for the reply. Much appreciated ;) :clinking_glasses:
